name: Pull request checks
on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main
    paths:
      - '**.ts, **.tsx'
  workflow_dispatch:
  push:
jobs:
  Code-Analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: Getting the code
        uses: actions/checkout@v3
      - name: Installing Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.31.2
      - name: Running linter
        run: deno lint
      - name: Cheking formatting
        run: 'deno fmt --check'
      - name: Running unit tests
        run: 'deno task test' 
