name: Pull request checks
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main
    paths:
      - '**.ts'
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Getting the code
        uses: actions/checkout@v3
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.30.3
      - name: Runnig unit tests
        run: "deno task test" 
